BlogBundle\Entity\Tag:
    properties:
        name:
            - NotBlank: { message: "El nombre no puede estar vacio" }
            - Length:
                min: 2
                minMessage: "El nombre tiene que tener mas de 2 caracteres" 
                
BlogBundle\Entity\Category:
    properties:
        name:
            - NotBlank: { message: "El nombre no puede estar vacio" }
            - Length:
                min: 2
                minMessage: "El nombre tiene que tener mas de 2 caracteres" 