BlogBundle\Entity\Entry:
    type: entity
    table: entries
    repositoryClass: BlogBundle\Repository\EntryRepository
    indexes:
        fk_entries_users:
            columns:
                - user_id
        fk_entries_categories:
            columns:
                - categories_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        content:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        status:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        image:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: entry
            joinColumns:
                categories_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    oneToMany:
        entryTag:
            targetEntity: EntryTag
            mappedBy: entry
            cascade: ["persist"]
    lifecycleCallbacks: {  }
