BlogBundle\Entity\Tag:
    type: entity
    table: tags
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
    oneToMany:
        entryTag:
            targetEntity: EntryTag
            mappedBy: tag
            cascade: ["persist"]
    lifecycleCallbacks: {  }
